# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and test status

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  tests-py3:
    name: Runs tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    - name: Test by decompiling a script and building un.rpyc
      run: |
        ./unrpyc.py --clobber "testcases/compiled/**/*.rpyc"
        diff -ur testcases/expected testcases/compiled -x "*.rpyc"
      # cd un.rpyc;
      # ./compile.py -p 1
      # cd ..
